//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist_Songs
    {
        public int ID_Playlist { get; set; }
        public int ID_Song { get; set; }
    
        public virtual Playlists Playlists { get; set; }
        public virtual Songs Songs { get; set; }
        public virtual Playlists Playlists1 { get; set; }
    }
}
